AllCops:
  Exclude:
    - tmp/**

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

StringLiterals:
  Enabled: false

LineLength:
  Enabled: false
